environment: "development" #development, staging, production

logging:
  level: "INFO"
  format: "[%(levelname)s] %(asctime)s - %(name)s - %(message)s"
  file: "logs/morph1x.log"
  max_file_size_mb: 100
  backup_count: 5

api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: false  
  log_level: "info"

video:
  source: "C:\\Users\\Admin\\github\\Morph1x"
  output_dir: "data/processed"
  save_output: false
  fps_output: 30

performance:
  batch_size: 1
  num_workers: 4
  prefetch_factor: 2
  use_gpu: true
  gpu_id: 0

monitoring:
  enable_metrics: true
  metrics_export_interval: 10  
  slow_request_threshold: 1.0  

security:
  cors_origins: ["*"]
  allowed_methods: ["GET", "POST"]
  max_concurrent_requests: 10

cache:
  enable: true
  ttl_seconds: 3600
  max_size_mb: 500

error_handling:
  retry_attempts: 3
  retry_delay_ms: 1000
  timeout_seconds: 30
